### ISSUE TITLE
How can I shade in dependencies in my final jar when executing the install task?

### ISSUE THREAD

**Issue by SupaHam** [johnrengelman/shadow#120]
I'm writing a library and I'd like the users of said library to be able to easily shade in my library dependency, and get the shaded version of my final library jar shaded, instead of just the library's code. Is that possible?

**Comment by jaysonminard** [comment]
I think we have a similar use case.

We want to shade Jackson, and a library we use jackson-kotlin-module uses Jackson as well.  So if we shade Jackson for us, we also want to shade it in our dependency so that both our code and jackson-kotlin-module use the new shaded version.  Otherwise we can't really control what classes we are using top to bottom. 

This is a very common problem when running in say, HADOOP where it adds crap old versions to the front of your class path and you want to avoid using them.  So you shade your dependencies, but then the dependencies of those dependencies screw you over by using the version from HADOOP on accident.  

We need to reinvent the used dependency.

**Comment by dkandalov** [comment]
I have the same question. 
I didn't find anything here http://imperceptiblethoughts.com/shadow/ so it looks strange that this issue is closed without explanation :(

**Comment by dkandalov** [comment]
In case this is useful, I found the following workaround:
 - use mave-publish plugin as described here http://imperceptiblethoughts.com/shadow/#publishing_with_maven_publish_plugin except for using local repository:
```
publishing {
	publications {
		shadow(MavenPublication) {
			from components.shadow
		}
	}
	repositories {
		mavenLocal() // <-- this 
	}
}
```
 - in myProject.gradle configure shadow to overwrite normal jar:
```
shadowJar {
	baseName = 'myProject'
	version = version
	classifier = null
}
```
 - run `clean install publish`

**Comment by johnrengelman** [comment]
It's closed because there was no additional information and it isn't clear what the OP was asking for.
@dkandalov what you are doing is documented in the user guide so I'm not sure how what you mean by there's no information there.

**Comment by dkandalov** [comment]
My understanding of the questions was "when I run install command it doesn't use shadow and I get thin files in local repository, how can make install use shadow?".

After following instructions from here http://imperceptiblethoughts.com/shadow/#publishing_with_maven_publish_plugin I ended up with thin jar and "-all" jar in local repository, so my dependant project couldn't see shadowed jar. If I used just "publish" (as mentioned on the page), then there was no source code jar installed in local repo. Overall, IMHO the setup I mentioned above is not obvious.

Otherwise, it's a great plugin! I really like it, especially after spending several hours with fatJar/jarjar :)

**Comment by dkandalov** [comment]
> I'm not sure how what you mean by there's no information there
I mean on this page http://imperceptiblethoughts.com/shadow/ there are two mentions of the word "install" and they are not related to install task.

**Comment by johnrengelman** [comment]
Shadow integrates with the Application plugin and provides a separate task to handle the shadow jar - as documented here: http://imperceptiblethoughts.com/shadow/#integrating_with_application_plugin and if you looked for "install" you would see that the documents state that a "installShadowApp" task is created.

> Additionally, the plugin will create the installShadowApp and startShadowScripts tasks which stages the necessary files for a distribution to build/installShadow

**Comment by johnrengelman** [comment]
IMO this is addressed. It's not in the scope of shadow to replace existing task's behavior. If a user is knowledgable enough about Gradle, they can configure their build, but doing so is outside of the scope of this project/user guide.
