### ISSUE TITLE
Running together with a plugin that depends on jar

### ISSUE THREAD

**Issue by Vad1mo** [johnrengelman/shadow#134]
I would like to use this plugin to shadow multiple jars into one and after that use the output for the [gradle-ikvm-plugin](https://github.com/Ullink/gradle-ikvm-plugin)

In my current setup if I call shadowJar and it creates the correct shadowJar but ikvm depends on jar so when I call `gradle  ikvm` it builds the jar and overrides my shadowJar and then makes a dll. 

My first approach was to override jar task and call shadowJar instead. But this seems not work as the result after `gradle jar`is a not shadowed file.
```
task jar(type: Jar, overwrite: true) {
    manifest {
        attributes 'Implementation-Title': 'Gradle Quickstart', 'Implementation-Version': version
    }
    shadowJar
}
````
My second approach was to add ordering that did also not work.

```
shadowJar.mustRunAfter jar
```

My Question is how can I modify my config so every time _jar_ runs it actually executes _shdowJar_  instead. So the ikvm plugin and other plugins that depend on the jar task continue to work.

**Comment by Vad1mo** [comment]
Found a solution, the way to go is this:
```
jar {
    manifest {
        attributes 'Implementation-Title': 'Gradle Quickstart', 'Implementation-Version': version
    }
    doLast { shadowJar.execute() }
}

```

**Comment by johnrengelman** [comment]
`execute` isn't a public API so I would suggest against using it. 
Does `jar.dependsOn shadowJar` not work for you? Are you trying to output the shadowJar into the same location as the regular Jar file? In that case I would do something like this:

```
jar.finalizedBy shadowJar
```

This isn't really optimal and you should ping the Ikvm developers about making the changing their code so that instead of relying on the `jar` task, they should take an input file and convention map it to the output of the `jar` task. That would allow you to override it with the output from a different task.
