### ISSUE TITLE
Are there plans to implement transitive dependencies exclusion?

### ISSUE THREAD

**Issue by loki2302** [johnrengelman/shadow#141]
The README says:
> Exclude specific dependency (transitive dependencies are not excluded).

Are there plans to allow for transitive dependencies exclusion as well? My case is bundling an application for [Apache Spark](https://spark.apache.org/docs/1.2.0/submitting-applications.html):
> If your code depends on other projects, you will need to package them alongside your application in order to distribute the code to a Spark cluster. To do this, to **create an assembly jar (or “uber” jar)** containing your code and its dependencies. Both sbt and Maven have assembly plugins. When creating assembly jars, **list Spark and Hadoop as provided dependencies**; these need not be bundled since they are provided by the cluster manager at runtime.

**Comment by johnrengelman** [comment]
In this case you would what they are describing. Add the spark dependencies to a "provided" configuration instead of compile/runtime. Then they (and their transitives) won't be included in the shadow jar. Just google for "gradle provided dependencies" and you should find some resources. I think there is a plugin out there as well.

**Comment by loki2302** [comment]
Hi @johnrengelman,

Thank you for advice. It indeed appeared quite easy to resolve.
