### ISSUE TITLE
Support deterministic (timestamp-free) output

### ISSUE THREAD

**Issue by blendmaster** [johnrengelman/shadow#229]
Ideally, two `./gradlew clean shadow` runs from identical sources will produce byte-identical outputs. Currently, the outputs have timestamps set to `now()` and I think the order of files in the jar can sometimes change.

This is important for reproducible verified builds, but I personally have a different use case: I develop hadoop jobs locally, produce a shadow jar, rsync the jar to a remote machine, and run the result. Unfortunately, since the timestamps are all different, rsync's delta detection algorithm is thrown off and it essentially has to re-upload the entire jar. However, if I preprocess the jar with this script:

```java
import java.util.zip.*;
import java.nio.file.attribute.FileTime;

public class EpochJar {
public static void main(String[] args) throws Throwable {
  FileTime epoch = FileTime.fromMillis(0);
  try (
    ZipOutputStream o = new ZipOutputStream(System.out);
    ZipInputStream i = new ZipInputStream(System.in)
  ) {
    byte[] buffer = new byte[8192];
    for (ZipEntry z = i.getNextEntry(); z != null; z = i.getNextEntry()) {
      o.putNextEntry(z.setCreationTime(epoch)
                      .setLastAccessTime(epoch)
                      .setLastModifiedTime(epoch));

      int n;
      while ((n = i.read(buffer, 0, buffer.length)) > 0) {
          o.write(buffer, 0, n);
      }
    }
  }
}
}
```

Then rsync works as expected, only transferring the (small) changes. 

Supporting deterministic outputs throughout gradle is a [larger issue][0], but I think it'd be nice for shadow itself to have an option to strip timestamps from its output.

[0]: https://discuss.gradle.org/t/feature-request-reproducible-jars/15505

**Comment by johnrengelman** [comment]
I feel this type of support is beyond the scope of Shadow. Especially since it's not supported by the larger Gradle framework w.r.t. JAR creation.

You can see my investigations into this same thing here: http://imperceptiblethoughts.com/2013/12/19/reproducible-multi-project-gradle-builds-part-2.html

**Comment by blendmaster** [comment]
Thanks for the blog post, it was linked in couple other mailing lists as `http://imperceptiblethoughts.com/post/70592053189/reproducible-multi-project-gradle-builds-part-2` which is now a dead link.

Well, it does seem unfortunately difficult to get reproducible builds in gradle. I'd be happy with just "rsyncable" jars though. Do you know any good places to hook in and reset the ZipFileEntry timestamp in shadow or in the underlying gradle machinery (instead of having to munge the jar after the build)? My cursory investigation didn't reveal any obvious places. `faketime` unfortunately breaks gradle in other ways, or i'd use that.

**Comment by AgentME** [comment]
Could this be revisited since Gradle as of v3.4 [supports](https://docs.gradle.org/4.8/userguide/working_with_files.html#sec:reproducible_archives) reproducible builds of archives?

```
jar {
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}
```

This works for the jar task, but doesn't seem to be fully respected by the shadowJar task.

(There is [gradle-reproducible-builds-plugin](https://github.com/Johni0702/gradle-reproducible-builds-plugin) which works with the shadow plugin, but in a seemingly slower-than-necessary hacky way: it repacks the jar after shadow does its thing.)
