### ISSUE TITLE
constants are also shaded?

### ISSUE THREAD

**Issue by zxcware** [johnrengelman/shadow#338]
Hi team, 

While shading, with `relocate('kafka', 'prefix.kafka')`, a configuration string `kafka.schema.url` is transformed to `prefix.kafka.schema.url`. 

Could you confirm if that's the case? Thanks.

**Comment by johnrengelman** [comment]
yeah, that's the nature of how the relocation works. It's just looking for string constants. The only work around is to use more specific package relocation directives. Maven has this same usability issue (https://issues.apache.org/jira/browse/MSHADE-156).

Unfortunately, there isn't a good way to account for this because a user might have a class name in a constant and then looking that class up with `Class.loadClass(name)`.

**Comment by zxcware** [comment]
Ah. I see. The point is to relocate class names in reflection.
