### ISSUE TITLE
how can I relocate all packages with a prefix

### ISSUE THREAD

**Issue by highsense** [johnrengelman/shadow#372]
I want to add a prefix for all the packages,just like:
org.slf4j ---> shade.org.slf4j

Actually there are so many packages in the dependencies that i don't want to config one by one mannually.Is there any way to use wildcard int relocate config. Such like :
`shadowJar {
   relocate '*','shade.*'
}`
 
### Shadow Version
2.0.3
### Gradle Version
4.1
### Gradle Build Script(s)
`shadowJar {
   relocate 'org.slf4j',null
}`

**Comment by johnrengelman** [comment]
Nothing built in, but you can see how I do this for Shadow itself when building the plugin - https://github.com/johnrengelman/shadow/blob/master/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ConfigureShadowRelocation.groovy#L28-L45

You can do something similar. This is a fairly expensive task since it requires scanning every jar file on the classpath. It also likely that you are over optimizing in this case.

**Comment by Blu3cr0ss** [comment]
shadow plugin is 7.1.2 version now, is there something built-in now?
