### ISSUE TITLE
Plugin does not accept new Java plugin configuration

### ISSUE THREAD

**Issue by sebukoleth** [johnrengelman/shadow#387]
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Shadow Version
2.0.4
### Gradle Version
4.7
### Expected Behavior
Gradle Java plugin-in has deprecated compile, runtime, testCompile and testRuntime configurations. Their replacements are: implementation, runtimeOnly, testImplementation and testRuntimeOnly. Therefore it must be possible to specify 

shadowJar {
    configurations = [project.configurations.implementation]
    classifier = null
}
### Actual Behavior
Error is raised "Resolving configuration 'implementation' directly is not allowed"

**Comment by johnrengelman** [comment]
@sebukoleth this isn't acutally correct. The `api` and `implementation` configurations are not consumable by the user as defined here: https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation. This includes other plugins.

The plugin currently configures `runtimeClasspath` as the configuration if it is present (otherwise it falls back to the deprecated `runtime` configuration). This is the correct behavior.
