### ISSUE TITLE
PropertiesFileTransformer break reproducible builds

### ISSUE THREAD

**Issue by chrko** [johnrengelman/shadow#584]
### Shadow Version
6.0.0
### Gradle Version
6.5.1
### Expected Behavior
Reproducible build = hash of resulting file within `build/lib`
### Actual Behavior
The `PropertiesFileTransformer` writes the current time into the generated files which breaks the reproducible build.
### Gradle Build Script(s)
I'm currently trying to build a fat application jar with spring dependencies and applying the following: https://github.com/spring-projects/spring-boot/issues/1828#issuecomment-231104288

```
shadowJar {
    mergeServiceFiles()
    transform(PropertiesFileTransformer) {
        paths = [
                'META-INF/spring.handlers',
                'META-INF/spring.factories',
                'META-INF/spring.schemas',
                'META-INF/spring.tooling',
        ]
        mergeStrategy = "latest"
    }
}
```

I will try to reduce my current `build.gradle` to ease reproduction and will append this.

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)
…
META-INF/services/org.apache.logging.log4j.util.PropertySource
META-INF/spring.handlers
META-INF/spring.schemas
META-INF/spring.tooling
META-INF/spring.factories

Content of spring.factories:
```
#
#Tue Jun 30 22:03:02 CEST 2020
org.springframework.beans.BeanInfoFactory=org.springframework.beans.ExtendedBeanInfoFactory
```

**Comment by crafton** [comment]
@chrko Did you find a way around this?

**Comment by ahmed-anas** [comment]
facing this issue. any workaround?

**Comment by gergogera** [comment]
This happens because [PropertiesFileTransformer](https://github.com/johnrengelman/shadow/blob/master/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformer.groovy#L241) is using [Properties store](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/java/util/Properties.java#L908)method which will add the timestamp anyways. Would be nice to change this so that the unnecessary time comment is removed instead.

**Comment by k-brooks** [comment]
I believe the intent of https://github.com/johnrengelman/shadow/pull/622 was to address this issue, however, it is still present.

**Comment by johnrengelman** [comment]
Introduced CleanProperties in 8 or 8.1. 
This shoudl work now.
