### ISSUE TITLE
How to get rid of "Multiple publications with coordinates 'XXX' are published to repository 'YYY'. The publications will overwrite each other!"

### ISSUE THREAD

**Issue by mikhailian** [johnrengelman/shadow#598]
### Shadow Version

5.2.0

### Gradle Version

5.6.2

### Background

The following publishes a fat jar and a pom with no dependencies.

```kotlin
publishing {
    publications {
        create<MavenPublication>("publishMaven") {
            artifact(tasks["shadowJar"])
        }
    }
}
tasks {
    shadowJar {
       archiveClassifier.set("")
    }
}
```
### Question

However, during the publishing, gradle complains about   "Multiple publications with coordinates 'XXX' are published to repository 'YYY'. The publications will overwrite each other!"

Is there a way to fix this warning? Would the suggestion of #563 be the right way to go?

**Comment by kdubb** [comment]
@mikhailian This is an old issue, but since people might land here after searching...

When you apply the plugin it automatically adds a publication for you [see docs](https://imperceptiblethoughts.com/shadow/publishing/#publishing-with-maven-publish-plugin).  So it appears you are repeating what the plugin does and duplicating the publication.

**Comment by mikhailian** [comment]
I do not have access to the project that exhibited the problem anymore, but just out of curiosity: what's the correct code,
```
tasks {
    shadowJar {
       archiveClassifier.set("")
    }
}
```
?

**Comment by kdubb** [comment]
Yes that looks right.

We found it easier to use the `ShadowJar` tasks as need and never actually apply the plugin. Then we could control the publishing without competing with the default plugin behavior.
