### ISSUE TITLE
Publish 7.1.0 artifacts to Gradle Plugin Portal

### ISSUE THREAD

**Issue by k-mack** [johnrengelman/shadow#716]
### Shadow Version

7.1.0

### Expected Behavior

The following build script resolves Shadow 7.1.0:

```gradle
// build.gradle
plugins {
  id 'java'
}

repositories {
  gradlePluginPortal()
}

dependencies {
  implementation "gradle.plugin.com.github.jengelman.gradle.plugins:shadow:7.1.0"
}
```

### Actual Behavior

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find gradle.plugin.com.github.jengelman.gradle.plugins:shadow:7.1.0.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/gradle/plugin/com/github/jengelman/gradle/plugins/shadow/7.1.0/shadow-7.1.0.pom
     Required by:
         project :
```

**Comment by johnrengelman** [comment]
They are there - https://plugins.gradle.org/m2/gradle/plugin/com/github/johnrengelman/shadow/7.1.0/

**Comment by johnrengelman** [comment]
Ah I see, you have the wrong GAV coordinates. The group should be `gradle.plugin.com.github.johnrengelman` (no trailing `gradle.plugins` at the end of it.

**Comment by johnrengelman** [comment]
I'm not sure why those coordinates changes between 7.0.0 and 7.1.0, but they did. 
I suspect it's because with me ripping out more of the legacy configuration for publishing to jcenter, that things reverted to a more normal state.

Sorry about that. I thought this had happened in 7.0.0 already. I'll add a note to the release notes about this.
I believe the GAV coordinates for 7.1.0 are the correct ones going forward as it aligns the GAV coordinates with the plugin ID (which they weren't before `jengelman` vs `johnrengelman`).

**Comment by chehsunliu** [comment]
The configurations of [v7.1.0](https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow/7.1.0) and [v7.0.0](https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow/7.0.0) shown on Gradle Plugin Portal are different.

To specify it as a plugin dependency, I have to use

```
gradle.plugin.com.github.jengelman.gradle.plugins:shadow:7.0.0
```

for `v7.0.0` and

```
gradle.plugin.com.github.johnrengelman:shadow:7.1.0
```

for `v7.1.0`.

**Comment by johnrengelman** [comment]
I've updated the change log to reflect this difference. https://imperceptiblethoughts.com/shadow/changes/#v7-1-0-2021-10-04
