### ISSUE TITLE
how to exclude the third party dependencies of dependeny

### ISSUE THREAD

**Issue by xiaochao00** [johnrengelman/shadow#804]
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Shadow Version
7.1.2
### Gradle Version
7.1.1
### Expected Behavior
Such as, the project A have dependency B, the project B have too many dependencies: C1,C2,....Cn, and maybe the project Cn have other dependencies;
I want to exclude B, the B\`s dependencies and the dependency\`s dependencies; but I couldn`t do it.
### Actual Behavior
I can only exclude B;
### Gradle Build Script(s)
```
shadowJar {
  dependencies {
    exclude(dependency('BGroup:BModule'))
  }
}
```

**Comment by johnrengelman** [comment]
This has been asked multiple times in the issues. It is not currently possible because there is not an intelligent way to decide what can and can't be excluded.
Say a dependency (C) is a transitive of both direct dependencies A and B. Now you exclude dependency B. What do you do with C? Is it included because you've included A? Or do you exclude it because you excluded B?

Now go, 3+ transitive dependencies deep.

This isn't something I'm going to implement directly in this project.
