### ISSUE TITLE
Cannot seem to make shadow jar work in multi project builds

### ISSUE THREAD

**Issue by kavink** [johnrengelman/shadow#96]
I have a multi project build , As follows , I want to make a fat jar of subprj1 and subprj2 and subprj3 want to keep it as thin jar.

But when i add shadow plugin. it does not make a fat jar of subprj1, instead makes a thin jar. When i add shadow jar to all subprojects. It does make a fat jar for subprj2 and subprj3, 

Is this the desired behavior ?
```
project(':subprj1') {
    shadowJar {}
    dependencies {
        //deps here
    }
}
project(':subprj2') {
    dependencies {
    compile project(':subprj1')
    }
}

project(':subprj3') {
    dependencies {
    compile project(':subprj1')
    }
}
```

**Comment by melodious** [comment]
I am also having problems with shadowjar task not including dependent sub-projects in the fat jar. I have a project with the following structure with 2 included projects - subproject1 & subproject2:
```
--rootProject
|
 --components
 |
   --subproject1
   --subproject2      
```
in the root project I have configured the sub-projects:
```
subprojects {
  apply plugin: 'java'
  apply plugin: 'scala'
  apply plugin: "com.github.johnrengelman.shadow"

  shadowJar {
    transform(AppendingTransformer) {
      resource = "reference.conf"
    }

    transform(AppendingTransformer) {
      resource = "META-INF/spring.tooling"
    }

    transform(AppendingTransformer) {
      resource = "META-INF/spring.schemas"
    }

    transform(AppendingTransformer) {
      resource = "META-INF/spring.handlers"
    }
    transform(ApacheLicenseResourceTransformer)
  }
}
```
subproject2 has a compile dependency on subproject1:
```
dependencies {
  compile(":components:subproject1")
}
```

When I run the 'gradle shadowjar' none of subproject1 source code or resources is in the fat jar for subproject2. How should I configure this so that my fat jar includes project dependencies?

Thanks.

**Comment by johnrengelman** [comment]
What version of the plugin, what version of Gradle? 
What you are doing is supported and verified by unit tests: https://github.com/johnrengelman/shadow/blob/master/src/test/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPluginSpec.groovy#L149

**Comment by johnrengelman** [comment]
if you can put together a minimal example that exhibits the problem and push it to a repo so I can clone it and check it out then I can look into it more.

**Comment by melodious** [comment]
I am using gradle 2.2.1. I will try to put something together.

**Comment by melodious** [comment]
I figured out why it wasn't working. In order to get scalaConsole to work, I added: 
```
  scalaConsole.classpath += sourceSets.main.output
  scalaTestConsole.classpath += sourceSets.test.output
```
This caused a warning from Gradle and consequently also caused the shadow jar not to include dependent project code in the fat jar. I still need that configuration in order to use the scalaConsole and after changing it to the following, the Gradle warning messgae is gone and the shadowjar now includes the sub project code.
```
  scalaConsole {
    dependsOn(compileScala, compileTestScala)
    doLast {
      classpath += sourceSets.main.output
      classpath += sourceSets.test.output
    }
  }
```
